# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'global_rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setMinimumSize(QtCore.QSize(180, 0))
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 0, 0, 1, 1)
        self.label_icon = QtWidgets.QLabel(Form)
        self.label_icon.setMinimumSize(QtCore.QSize(28, 28))
        self.label_icon.setObjectName("label_icon")
        self.gridLayout_2.addWidget(self.label_icon, 0, 2, 1, 1)
        self.checkBox_display = QtWidgets.QCheckBox(Form)
        self.checkBox_display.setObjectName("checkBox_display")
        self.gridLayout_2.addWidget(self.checkBox_display, 0, 5, 1, 1)
        self.lineEdit_find = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_find.sizePolicy().hasHeightForWidth())
        self.lineEdit_find.setSizePolicy(sizePolicy)
        self.lineEdit_find.setMinimumSize(QtCore.QSize(80, 28))
        self.lineEdit_find.setObjectName("lineEdit_find")
        self.gridLayout_2.addWidget(self.lineEdit_find, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(Form)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 0, 3, 1, 1)
        self.pushButton_sure = QtWidgets.QPushButton(Form)
        self.pushButton_sure.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_sure.setObjectName("pushButton_sure")
        self.gridLayout.addWidget(self.pushButton_sure, 0, 4, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.table_options = QtWidgets.QTableWidget(Form)
        self.table_options.setObjectName("table_options")
        self.table_options.setColumnCount(0)
        self.table_options.setRowCount(0)
        self.gridLayout_3.addWidget(self.table_options, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(58, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem3, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_icon.setText(_translate("Form", "icon"))
        self.checkBox_display.setText(_translate("Form", "表格视图"))
        self.pushButton_cancel.setText(_translate("Form", "取消"))
        self.pushButton_sure.setText(_translate("Form", "确定"))
