# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(440, 230)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_game = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_game.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_game.setObjectName("lineEdit_game")
        self.gridLayout_4.addWidget(self.lineEdit_game, 1, 0, 1, 1)
        self.pushButton_open = QtWidgets.QPushButton(self.frame)
        self.pushButton_open.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_open.setObjectName("pushButton_open")
        self.gridLayout_4.addWidget(self.pushButton_open, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_auto_save_rules = QtWidgets.QCheckBox(self.frame)
        self.checkBox_auto_save_rules.setObjectName("checkBox_auto_save_rules")
        self.gridLayout_2.addWidget(self.checkBox_auto_save_rules, 0, 1, 1, 1)
        self.checkBox_use_theme = QtWidgets.QCheckBox(self.frame)
        self.checkBox_use_theme.setObjectName("checkBox_use_theme")
        self.gridLayout_2.addWidget(self.checkBox_use_theme, 0, 0, 1, 1)
        self.checkBox_pro = QtWidgets.QCheckBox(self.frame)
        self.checkBox_pro.setObjectName("checkBox_pro")
        self.gridLayout_2.addWidget(self.checkBox_pro, 1, 0, 1, 1)
        self.checkBox_auto_save_desc = QtWidgets.QCheckBox(self.frame)
        self.checkBox_auto_save_desc.setObjectName("checkBox_auto_save_desc")
        self.gridLayout_2.addWidget(self.checkBox_auto_save_desc, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 3, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 4, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(self.frame)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 0, 1, 1, 1)
        self.pushButton_sure = QtWidgets.QPushButton(self.frame)
        self.pushButton_sure.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_sure.setObjectName("pushButton_sure")
        self.gridLayout.addWidget(self.pushButton_sure, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 5, 0, 1, 2)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "游戏路径 (加-win可窗口启动)"))
        self.pushButton_open.setText(_translate("Form", "浏览文件"))
        self.checkBox_auto_save_rules.setText(_translate("Form", "关闭时保存修改"))
        self.checkBox_use_theme.setText(_translate("Form", "使用暗色主题"))
        self.checkBox_pro.setText(_translate("Form", "默认专业模式"))
        self.checkBox_auto_save_desc.setText(_translate("Form", "关闭时保存描述"))
        self.pushButton_cancel.setText(_translate("Form", "取消"))
        self.pushButton_sure.setText(_translate("Form", "确定"))
